# Generated by Django 4.2.4 on 2023-12-17 13:52

import account.models
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=45, null=True, unique=True, verbose_name='email_address')),
                ('referral_code', models.CharField(blank=True, default=None, max_length=12, null=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('is_verified', models.BooleanField(blank=True, default=False, null=True)),
                ('otp', models.CharField(blank=True, max_length=9, null=True)),
                ('uidb', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('has_invested', models.BooleanField(default=False, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('t_and_c', models.BooleanField(default=False)),
                ('auth_providers', models.CharField(default='email', max_length=50)),
                ('has_updated_name', models.BooleanField(default=False, null=True)),
                ('ping_url', models.URLField(default=None, max_length=60, null=True)),
                ('profile_completed', models.BooleanField(default=False, null=True)),
                ('is_subscribed', models.BooleanField(default=True, null=True)),
                ('is_ambassador', models.BooleanField(blank=True, default=False, null=True)),
                ('bvn', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('address', models.TextField(blank=True, default=None, max_length=400, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('middle_name', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ('-date_joined',),
                'indexes': [models.Index(fields=['id', 'email'], name='account_cus_id_f150a4_idx')],
            },
            managers=[
                ('objects', account.models.UserManager()),
            ],
        ),
    ]
